export const environment = {
  production: true,
  envName: 'prod',
  base_prefix: '/fad',
  searchapiurl: 'http://test.com',
  locationapiurl: 'http://test.com',
  specialtyapiurl: 'http://test.com',
  planselectionapiurl: 'http://test.com',
  OPA_GOV_LINK: 'http://www.opa.ca.gov',
  DEPT_INS_HEALTH_COMPARE: 'http://www.consumerreports.org/cro/health/california-health-cost-and-quality---consumer-reports/index.html',
  CMS_HOSPITAL_COMPARE: 'https://www.medicare.gov/hospitalcompare/search.html',
  CMS_PHYSICIAN_QUALITY: 'https://www.cms.gov/Medicare/Quality-Initiatives-Patient-Assessment-instruments/PQRS/index.html?redirect=/pqri/',
  MEMBER_LOGIN: '/bsca/bsc/public/member/mp/login/',
  SECURE_OPINION: 'https://secure.opinionlab.com/ccc01/comment_card_d.asp',
  PROVIDER_BCBS: 'https://provider.bcbs.com/app/public/#/one/city=&state=&postalCode=&country=&insurerCode=BCBSA_I&brandCode=BCBSANDHF&alphaPrefix=AAA&bcbsaProductId',
  COVERAGE_BCBC: 'https://www.bluecardworldwide.com/Account/Login/',
  BLUECARD_WORLDWIDE: 'https://www.bluecardworldwide.com/',
  BLUESHIELD_CA_INSTA: 'https://www.instagram.com/blueshieldofca',
  BLUESHIELD_CA_TWITTER: 'https://twitter.com/blueshieldca',
  BLUESHIELD_CA_FB: 'https://www.facebook.com/BlueShieldCA',
  MEDIA_CENTER_URL: '/bsca/about-blue-shield/media-center/home.sp',
  SEARCH_PHARM_DIREC: 'https://www.blueshieldca.com/sites/medicare/plans-with-drug-coverage/prescription-drug-reference/pharmacy-directory.sp',
  MAIL_SERVICE: 'https://www.blueshieldca.com/bsca/pharmacy/mail-service-prescriptions.sp',
  NETWORK_SPECIALTY: 'https://www.blueshieldca.com/bsca/pharmacy/network-specialty-pharmacies.sp',
  MEDICARE_GOVT: 'https://www.medicare.gov/physiciancompare/',
  FEP_BLUE: 'https://www.fepblue.org/',
  HEALTH_CARE_OUTSIDE: 'https://provider.bcbs.com',
  VISION_CARE: ' https://www.mesvision.com/providerSearch.hsmo',
  MES_VISION_CARE: 'https://www.mesvision.com/providerSearch.hsmo',
  MES_DISCOUNT_PROVIDER: 'http://www.ecndiscount.com/homepage.htm',
  WEB_URL: 'https://www.webn212.bsc.bscal.com/bsca/bsc/wcm/connect/member/fad_content_'
};
